In [85]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [86]:
data2 = pd.read_csv('round_2_alloted.csv', sep=',', header=None)

In [87]:
data2 = data2.set_index(0)

In [88]:
data2.head()

,1,2,3,4,5,6,7,8,9
0,,,,,,,,,
1,1,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,NaN,NaN,NaN,Did Not Opt for\rUpgradation
2,4,"BANGALORE MED.\rCOLLEGE,BANGALORE",MBBS,NaN,NaN,NaN,NaN,NaN,Not Reported Seat\rCancelled
3,7,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,NaN,NaN,NaN,Did Not Opt for\rUpgradation
4,8,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,NaN,NaN,NaN,Did Not Opt for\rUpgradation
5,10,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,NaN,NaN,NaN,Not Reported Seat\rCancelled

In [89]:
data2[9].unique()

array(['Did Not Opt for\rUpgradation', 'Not Reported Seat\rCancelled',
       'Allotted seat from\rfresh choices', 'Allotted in 2nd Round',
       'No Upgradation', 'Did not fill up fresh\rchoices', 'Resigned',
       'Retained *', 'Admission of Previoud\rRound Cancelled'], dtype=object)

In [90]:
#data1 = data

In [91]:
data2.head()

,1,2,3,4,5,6,7,8,9
0,,,,,,,,,
1,1,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,NaN,NaN,NaN,Did Not Opt for\rUpgradation
2,4,"BANGALORE MED.\rCOLLEGE,BANGALORE",MBBS,NaN,NaN,NaN,NaN,NaN,Not Reported Seat\rCancelled
3,7,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,NaN,NaN,NaN,Did Not Opt for\rUpgradation
4,8,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,NaN,NaN,NaN,Did Not Opt for\rUpgradation
5,10,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,NaN,NaN,NaN,Not Reported Seat\rCancelled

In [92]:
mask = data2[9]=='Allotted seat from\rfresh choices'
data2.loc[mask,2]=data2.loc[mask,4]

In [93]:
data2[mask]

,1,2,3,4,5,6,7,8,9
0,,,,,,,,,
29,45,"LADY HARDINGE MEDICAL\rCOLLEGE, NEW DELHI",MBBS,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,1.0,Allotted seat from\rfresh choices
31,49,"University College of Medical\rSciences, Delhi",MBBS,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,1.0,Allotted seat from\rfresh choices
43,64,"GOVERNMENT MEDICAL\rCOLLEGE AND HOSPITAL,\rCHA...",MBBS,"VMMC AND SAFDARJUNG\rHOSPITAL, NEW DELHI",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices
45,67,"University College of Medical\rSciences, Delhi",MBBS,"VMMC AND SAFDARJUNG\rHOSPITAL, NEW DELHI",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices
85,119,"IMS BHU, Varanasi, UP",MBBS,"University College of Medical\rSciences, Delhi",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices
98,134,"NDMC Medical College, Delhi",MBBS,"LADY HARDINGE MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices
108,149,"MADRAS MEDICAL COLLEGE,\rCHENNAI",MBBS,"LADY HARDINGE MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices
111,152,"VMMC AND SAFDARJUNG\rHOSPITAL, NEW DELHI",MBBS,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,OBC,OBC,1.0,Allotted seat from\rfresh choices
113,154,"VMMC AND SAFDARJUNG\rHOSPITAL, NEW DELHI",MBBS,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,OBC,OBC,1.0,Allotted seat from\rfresh choices
115,157,"IMS BHU, Varanasi, UP",MBBS,"University College of Medical\rSciences, Delhi",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices
118,160,"GOVERNMENT MEDICAL\rCOLLEGE AND HOSPITAL,\rCHA...",MBBS,"University College of Medical\rSciences, Delhi",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices
121,163,"KGMC, LUCKNOW",MBBS,"University College of Medical\rSciences, Delhi",MBBS,UR,UR,3.0,Allotted seat from\rfresh choices
122,164,"SETH G.S. MEDICAL COLLEGE,\rMUMBAI",MBBS,"University College of Medical\rSciences, Delhi",MBBS,UR,UR,3.0,Allotted seat from\rfresh choices
144,193,"University College of Medical\rSciences, Delhi",MBBS,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,OBC,OBC,1.0,Allotted seat from\rfresh choices
154,206,"S.M.S. MEDICAL COLLEGE,\rJAIPUR",MBBS,"LADY HARDINGE MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,3.0,Allotted seat from\rfresh choices
180,236,"KGMC, LUCKNOW",MBBS,"LADY HARDINGE MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,1.0,Allotted seat from\rfresh choices
191,252,"LADY HARDINGE MEDICAL\rCOLLEGE, NEW DELHI",MBBS,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,OBC,OBC,1.0,Allotted seat from\rfresh choices
194,257,"LADY HARDINGE MEDICAL\rCOLLEGE, NEW DELHI",MBBS,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,OBC,OBC,1.0,Allotted seat from\rfresh choices
197,260,"PT. B.D. SHARMA PGIMS,\rROHTAK",MBBS,"GOVERNMENT MEDICAL\rCOLLEGE AND HOSPITAL,\rCHA...",MBBS,UR,UR,4.0,Allotted seat from\rfresh choices
202,266,"S.C.B. MEDICAL COLLEGE,\rCUTTACK",MBBS,"LADY HARDINGE MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices
206,270,"IMS BHU, Varanasi, UP",MBBS,"University College of Medical\rSciences, Delhi",MBBS,OBC,OBC,2.0,Allotted seat from\rfresh choices
210,274,"GRANT MEDICAL COLL & SIR\rJ.J.HOSP,MUMBAI",MBBS,"SETH G.S. MEDICAL COLLEGE,\rMUMBAI",MBBS,UR,UR,4.0,Allotted seat from\rfresh choices
214,278,"GOVT.MEDICAL COLLEGE,\rAMRITSAR",MBBS,"GOVERNMENT MEDICAL\rCOLLEGE AND HOSPITAL,\rCHA...",MBBS,UR,UR,3.0,Allotted seat from\rfresh choices
218,283,"S.M.S. MEDICAL COLLEGE,\rJAIPUR",MBBS,"Dr. B.S.A. Medical College,\rDelhi",MBBS,UR,UR,4.0,Allotted seat from\rfresh choices
222,288,"S.M.S. MEDICAL COLLEGE,\rJAIPUR",MBBS,"LADY HARDINGE MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,4.0,Allotted seat from\rfresh choices
224,290,"PT. B.D. SHARMA PGIMS,\rROHTAK",MBBS,"University College of Medical\rSciences, Delhi",MBBS,OBC,OBC,2.0,Allotted seat from\rfresh choices
227,293,"IMS BHU, Varanasi, UP",MBBS,"VMMC AND SAFDARJUNG\rHOSPITAL, NEW DELHI",MBBS,OBC,OBC,2.0,Allotted seat from\rfresh choices
229,297,"GRANT MEDICAL COLL & SIR\rJ.J.HOSP,MUMBAI",MBBS,"SETH G.S. MEDICAL COLLEGE,\rMUMBAI",MBBS,UR,UR,4.0,Allotted seat from\rfresh choices
234,302,"KGMC, LUCKNOW",MBBS,"University College of Medical\rSciences, Delhi",MBBS,OBC,OBC,2.0,Allotted seat from\rfresh choices
239,308,"KGMC, LUCKNOW",MBBS,"LADY HARDINGE MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,3.0,Allotted seat from\rfresh choices
...,...,...,...,...,...,...,...,...,...
6392,91950,"B.J. MEDICAL COLLEGE,\rAHMEDABAD",MBBS,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,OBC PH,OBC PH1,1.0,Allotted seat from\rfresh choices
6423,141177,"SARDAR PATEL MEDICAL\rCOLLEGE, BIKANER",MBBS,"S.M.S. MEDICAL COLLEGE,\rJAIPUR",MBBS,UR PH,OBC PH1,4.0,Allotted seat from\rfresh choices
6427,146004,"MEDICAL COLLEGE, BARODA",MBBS,"NDMC Medical College, Delhi",MBBS,UR PH,OBC PH1,4.0,Allotted seat from\rfresh choices
6428,155739,"Govt. Medical College, Kannauj",MBBS,"RURAL INST OF MED SCI &\rRESEARCH,SAIFAI",MBBS,UR PH,OBC PH1,3.0,Allotted seat from\rfresh choices
6430,161316,"MRA MEDICAL COLLEGE\rAMBEDKAR NAGAR, UP",MBBS,"Dr. B.S.A. Medical College,\rDelhi",MBBS,UR PH,OBC PH1,2.0,Allotted seat from\rfresh choices
6439,176286,"Indira Gandhi Institute of\rMedical Sciences, ...",MBBS,"Dr Ram Manohar Lohia Inst. of\rMed. Sce., Lucknow",MBBS,UR PH,OBC PH1,4.0,Allotted seat from\rfresh choices
6440,176442,"NETAJI SUBHASH CHANDRA\rBOSE MC,JABALPUR",MBBS,"L.L.R.M. MEDICAL COLLEGE,\rMEERUT",MBBS,UR PH,OBC PH1,9.0,Allotted seat from\rfresh choices
6447,184884,"GOVT.MEDICAL\rCOLLEGE,THIRUVANANTHAPUR\rAM",MBBS,"Darbhanga Medical College,\rLaheriasarai",MBBS,SC PH,SC PH2,3.0,Allotted seat from\rfresh choices
6450,191213,Andaman and Nicobar Islands\rInstitute of Medi...,MBBS,"Government Doon Medcial\rCollege, Dehradun",MBBS,UR PH,UR PH1,3.0,Allotted seat from\rfresh choices
6472,211476,"GOVERNMENT MEDICAL\rCOLLEGE, MIRAJ",MBBS,"MRA MEDICAL COLLEGE\rAMBEDKAR NAGAR, UP",MBBS,UR PH,OBC PH1,8.0,Allotted seat from\rfresh choices
6474,212965,"DR.RAJENDRA PRASAD MC,\rTANDA",MBBS,"GMC, Jalaun, UP",MBBS,UR PH,OBC PH1,17.0,Allotted seat from\rfresh choices
6477,217839,"INDIRA GANDHI MEDICAL\rCOLL., SHIMLA",MBBS,"GRANT MEDICAL COLL & SIR\rJ.J.HOSP,MUMBAI",MBBS,UR PH,UR PH1,9.0,Allotted seat from\rfresh choices
6487,227331,"Pt. D.D.U MEDICAL COLLEGE,\rRAJKOT",MBBS,"GOA MEDICAL COLLEGE,\rPANAJI",MBBS,UR PH,UR PH1,7.0,Allotted seat from\rfresh choices
6488,228869,"GURU GOVIND SINGH MED\rCOLL,FARIDKOT",MBBS,"R.N.T. MEDICAL COLLEGE,\rUDAIPUR",MBBS,UR PH,UR PH1,2.0,Allotted seat from\rfresh choices
6494,236827,"RAJIV GANDHI MEDICAL\rCOLLEGE, THANE",MBBS,"Dr. R. N. Cooper General\rHospital, Juhu, Mumbai",MBBS,UR PH,OBC PH1,4.0,Allotted seat from\rfresh choices
6497,242447,"Govt. Medical College and\rHospital, Chandrapur",MBBS,"Government Medical College,\rBanda",MBBS,UR PH,OBC PH1,3.0,Allotted seat from\rfresh choices
6529,271047,"MIDNAPORE MEDICAL\rCOLLEGE, MIDNAPUR",MBBS,"NILRATAN SIRKAR MEDICAL\rCOLLEGE, KOLKATA",MBBS,UR PH,OBC PH1,1.0,Allotted seat from\rfresh choices
6530,271320,"NORTH BENGAL\rMED.COLL,DARJEELING",MBBS,"RAJIV GANDHI MEDICAL\rCOLLEGE, THANE",MBBS,UR PH,OBC PH1,14.0,Allotted seat from\rfresh choices
6532,274009,"GOVT. KILPAUK MEDICAL\rCOLLEGE,CHENNAI",MBBS,"MADRAS MEDICAL COLLEGE,\rCHENNAI",MBBS,UR PH,OBC PH1,1.0,Allotted seat from\rfresh choices
6538,285743,"Fakhruddin Ali Ahmed Medical\rCollege, Barpeta",MBBS,"BUNDELKHAND MEDICAL\rCOLLEGE, SAGAR",MBBS,UR PH,UR PH1,27.0,Allotted seat from\rfresh choices
6550,306426,"GTMC, THIRUVARUR",MBBS,"CALCUTTA NATIONAL MED\rCOLL,KOLKATA",MBBS,UR PH,OBC PH1,11.0,Allotted seat from\rfresh choices
6552,306889,"K.A.P. VISWANATHAM\rG.M.C.,TIRUCHIRAPALLI",MBBS,"STANLEY MEDICAL COLLEGE,\rCHENNAI",MBBS,UR PH,UR PH1,2.0,Allotted seat from\rfresh choices
6554,311382,"GOVT. MOHAN\rKUMARAMANGALAM\rM.C.,SALEM",MBBS,"COLL OF MEDICINE & JNM\rHOSPITAL, KALYANI",MBBS,UR PH,OBC PH1,5.0,Allotted seat from\rfresh choices
6561,321730,"GOVT. DENTAL COLLEGE &\rHOSP,AHMEDABAD",BDS,"GOVT. MEDICAL\rCOLLEGE,PATIALA",MBBS,UR PH,UR PH1,22.0,Allotted seat from\rfresh choices
6563,325322,"THENI GOVT. MEDICAL\rCOLLEGE, THENI",MBBS,"B.J. MEDICAL COLLEGE,\rAHMEDABAD",MBBS,UR PH,UR PH1,25.0,Allotted seat from\rfresh choices
6582,363065,"GOVT. COLLEGE OF\rDENTISTRY, INDORE",BDS,"NETAJI SUBHASH CHANDRA\rBOSE MC,JABALPUR",MBBS,UR PH,OBC PH1,25.0,Allotted seat from\rfresh choices
6616,451909,"REGIONAL DENTAL COLLEGE,\rGUWAHATI",BDS,"MADRAS MEDICAL COLLEGE,\rCHENNAI",MBBS,SC PH,SC PH2,92.0,Allotted seat from\rfresh choices
6654,517672,"Darbhanga Medical College,\rLaheriasarai",MBBS,"JAWAHAR LAL NEHRU\rMEDICAL, AJMER",MBBS,ST PH,ST PH2,1.0,Allotted seat from\rfresh choices
6655,526589,Govt. Sivgangai M. C.\rSivagangai,MBBS,"S.N. MEDICAL COLLEGE,\rAGRA",MBBS,ST PH,ST PH1,9.0,Allotted seat from\rfresh choices
6660,533334,"BPS Govt. Med. College,\rSonepat",MBBS,"GOVT.MEDICAL COLLEGE,\rAMRITSAR",MBBS,SC PH,SC PH1,12.0,Allotted seat from\rfresh choices

In [74]:
data2[mask].head()

,1,2,3,4,5,6,7,8,9
0,,,,,,,,,
29,45,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,1.0,Allotted seat from\rfresh choices
31,49,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,1.0,Allotted seat from\rfresh choices
43,64,"VMMC AND SAFDARJUNG\rHOSPITAL, NEW DELHI",MBBS,"VMMC AND SAFDARJUNG\rHOSPITAL, NEW DELHI",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices
45,67,"VMMC AND SAFDARJUNG\rHOSPITAL, NEW DELHI",MBBS,"VMMC AND SAFDARJUNG\rHOSPITAL, NEW DELHI",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices
85,119,"University College of Medical\rSciences, Delhi",MBBS,"University College of Medical\rSciences, Delhi",MBBS,UR,UR,2.0,Allotted seat from\rfresh choices

In [40]:
data2 = data2.drop([4,9],axis=1)

In [41]:
data2 = data2.drop([5,8],axis=1)

In [42]:
data1 = pd.read_csv('round_1_alloted.csv',header = None)

In [43]:
data1 = data1.set_index(0)

In [44]:
data1.head()

    1                                         2     3   4   5         6
0
1   1  MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI  MBBS  UR  UR  Allotted
2   4          BANGALORE MED. COLLEGE,BANGALORE  MBBS  UR  UR  Allotted
3   7  MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI  MBBS  UR  UR  Allotted
4   8  MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI  MBBS  UR  UR  Allotted
5  10  MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI  MBBS  UR  UR  Allotted

In [45]:
data1 = data1.drop(6,axis=1)

In [46]:
data1.columns = ['Id', 'College','Course','6','7']

In [47]:
data1.head()

   Id                                   College Course   6   7
0
1   1  MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI   MBBS  UR  UR
2   4          BANGALORE MED. COLLEGE,BANGALORE   MBBS  UR  UR
3   7  MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI   MBBS  UR  UR
4   8  MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI   MBBS  UR  UR
5  10  MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI   MBBS  UR  UR

In [48]:
data2.columns = data1.columns

In [61]:
out_data = data2.merge(data1, on='Id',how='outer')

In [62]:
out_data

,Id,College_x,Course_x,6_x,7_x,College_y,Course_y,6_y,7_y
0,1,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
1,4,"BANGALORE MED.\rCOLLEGE,BANGALORE",MBBS,NaN,NaN,"BANGALORE MED. COLLEGE,BANGALORE",MBBS,UR,UR
2,7,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
3,8,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
4,10,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
5,12,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
6,15,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
7,17,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
8,18,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
9,19,"GOVT. MEDICAL COLLEGE,\rKOTTAYAM",MBBS,NaN,NaN,"GOVT. MEDICAL COLLEGE, KOTTAYAM",MBBS,UR,UR
10,20,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
11,21,"GOVERNMENT MEDICAL\rCOLLEGE, SURAT",MBBS,NaN,NaN,"GOVERNMENT MEDICAL COLLEGE, SURAT",MBBS,UR,UR
12,22,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
13,23,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
14,24,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
15,25,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
16,26,"SETH G.S. MEDICAL COLLEGE,\rMUMBAI",MBBS,NaN,NaN,"SETH G.S. MEDICAL COLLEGE, MUMBAI",MBBS,UR,UR
17,30,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
18,31,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
19,32,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
20,34,"BANGALORE MED.\rCOLLEGE,BANGALORE",MBBS,NaN,NaN,"BANGALORE MED. COLLEGE,BANGALORE",MBBS,UR,UR
21,35,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
22,36,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
23,37,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
24,38,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,NaN,NaN,"MAULANA AZAD MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
25,39,"GOVT.MEDICAL\rCOLLEGE,THIRUVANANTHAPUR\rAM",MBBS,NaN,NaN,"GOVT.MEDICAL\rCOLLEGE,THIRUVANANTHAPURAM",MBBS,UR,UR
26,41,"GOVT.MEDICAL\rCOLLEGE,THIRUVANANTHAPUR\rAM",MBBS,NaN,NaN,"GOVT.MEDICAL\rCOLLEGE,THIRUVANANTHAPURAM",MBBS,UR,UR
27,43,"IMS BHU, Varanasi, UP",MBBS,NaN,NaN,"IMS BHU, Varanasi, UP",MBBS,UR,UR
28,45,"MAULANA AZAD MEDICAL\rCOLLEGE, NEW DELHI",MBBS,UR,UR,"LADY HARDINGE MEDICAL COLLEGE, NEW\rDELHI",MBBS,UR,UR
29,48,NaN,NaN,UR,UR,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6613,514811,NaN,NaN,UR PH,OBC PH1,NaN,NaN,NaN,NaN
6614,516038,NaN,NaN,UR PH,ST PH1,NaN,NaN,NaN,NaN
6615,516199,NaN,NaN,UR PH,OBC PH1,NaN,NaN,NaN,NaN
6616,517108,NaN,NaN,UR PH,UR PH1,NaN,NaN,NaN,NaN
6617,517672,"JAWAHAR LAL NEHRU\rMEDICAL, AJMER",MBBS,ST PH,ST PH2,"Darbhanga Medical College, Laheriasarai",MBBS,ST PH,ST PH2
6618,526589,"S.N. MEDICAL COLLEGE,\rAGRA",MBBS,ST PH,ST PH1,Govt. Sivgangai M. C. Sivagangai,MBBS,ST PH,ST PH1
6619,530291,NaN,NaN,UR PH,UR PH1,NaN,NaN,NaN,NaN
6620,531574,NaN,NaN,UR PH,UR PH1,NaN,NaN,NaN,NaN
6621,531946,"VMMC AND SAFDARJUNG\rHOSPITAL, NEW DELHI",MBBS,NaN,NaN,"VMMC AND SAFDARJUNG HOSPITAL, NEW\rDELHI",MBBS,ST PH,ST PH1
6622,533284,Sh. Lal Bahadur Shastri Govt.\rMed. College. M...,MBBS,NaN,NaN,Sh. Lal Bahadur Shastri Govt. Med. College.\rM...,MBBS,ST PH,ST PH1
6623,533334,"GOVT.MEDICAL COLLEGE,\rAMRITSAR",MBBS,SC PH,SC PH1,"BPS Govt. Med. College, Sonepat",MBBS,SC PH,SC PH1
6624,541367,NaN,NaN,SC PH,SC PH2,NaN,NaN,NaN,NaN
6625,547950,NaN,NaN,SC PH,SC PH2,NaN,NaN,NaN,NaN
6626,551407,"CHENGALPATTU MEDICAL\rCOLL,CHENGALPATTU",MBBS,NaN,NaN,"CHENGALPATTU MEDICAL\rCOLL,CHENGALPATTU",MBBS,SC PH,SC PH1
6627,551965,"Karwar Institute of Medical\rSciences, Karwar",MBBS,NaN,NaN,"Karwar Institute of Medical Sciences, Karwar",MBBS,SC PH,SC PH1
6628,883,NaN,NaN,NaN,NaN,"BAHIRAMJEE JIJIBHAI MEDICAL COLLGE, PUNE",MBBS,UR,UR
6629,2408,NaN,NaN,NaN,NaN,"Government Doon Medcial College, Dehradun",MBBS,UR,UR
6630,2479,NaN,NaN,NaN,NaN,"M.P. SHAH MEDICAL COLLEGE, JAMNAGAR",MBBS,UR,OBC
6631,3840,NaN,NaN,NaN,NaN,"BELGAUM INST. OF MEDICAL SCI., BELGAUM",MBBS,UR,OBC
6632,3881,NaN,NaN,NaN,NaN,"Pt. Jawahar Lal Nehru Govt. Med. College,\rChamba",MBBS,UR,UR
6633,3901,NaN,NaN,NaN,NaN,Sheikh-Ul-Hind Maulana Mahmood Hasan\rMedical ...,MBBS,UR,UR
6634,5275,NaN,NaN,NaN,NaN,"Govt. Medical College and Hospital,\rChandrapur",MBBS,UR,UR
6635,5643,NaN,NaN,NaN,NaN,"MADRAS MEDICAL COLLEGE, CHENNAI",MBBS,SC,SC
6636,5745,NaN,NaN,NaN,NaN,"Jorhat Medical College and Hospital, JORHAT",MBBS,UR,OBC
6637,6502,NaN,NaN,NaN,NaN,"IMS BHU Dental, Varanasi, UP",BDS,UR,OBC
6638,12872,NaN,NaN,NaN,NaN,"S.C.B. MEDICAL COLLEGE, CUTTACK",MBBS,SC,SC
6639,14862,NaN,NaN,NaN,NaN,"G.R. MEDICAL COLLEGE, GWALIOR",MBBS,SC,SC
6640,28575,NaN,NaN,NaN,NaN,"Saheed Laxman Nayak Med. College and Hos.,\rKo...",MBBS,SC,SC
6641,59457,NaN,NaN,NaN,NaN,"THOOTHUKUDI MEDICAL\rCOLLEGE,THOOTHUKUDI",MBBS,ST,ST
6642,60543,NaN,NaN,NaN,NaN,"GTMC, THIRUVARUR",MBBS,ST,ST

In [63]:
mask = (out_data['6_y'].isnull())
#out_data.loc[mask,'6_y']=data.loc[mask,'6_x']
out_data[mask]

          Id College_x Course_x    6_x      7_x College_y Course_y  6_y  7_y
29        48       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
136      185       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
152      205       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
158      213       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
165      220       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
175      232       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
266      341       NaN      NaN    OBC      OBC       NaN      NaN  NaN  NaN
290      369       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
292      371       NaN      NaN    OBC      OBC       NaN      NaN  NaN  NaN
297      377       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
301      382       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
302      384       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
319      408       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
330      421       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
383      491       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
404      525       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
406      527       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
414      539       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
453      607       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
454      608       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
467      624       NaN      NaN     UR      OBC       NaN      NaN  NaN  NaN
486      651       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
504      679       NaN      NaN    OBC      OBC       NaN      NaN  NaN  NaN
521      701       NaN      NaN     UR      OBC       NaN      NaN  NaN  NaN
546      739       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
552      748       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
558      754       NaN      NaN     UR      OBC       NaN      NaN  NaN  NaN
585      801       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
586      802       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
590      810       NaN      NaN     UR       UR       NaN      NaN  NaN  NaN
...      ...       ...      ...    ...      ...       ...      ...  ...  ...
6584  466711       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6586  468969       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6590  475536       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6591  477920       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6592  478878       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6593  480040       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6595  483493       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6596  485015       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6598  486726       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6599  487222       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6600  487511       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6601  493911       NaN      NaN  SC PH   SC PH1       NaN      NaN  NaN  NaN
6603  498202       NaN      NaN  SC PH   SC PH2       NaN      NaN  NaN  NaN
6604  502645       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6605  502760       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6606  502884       NaN      NaN  SC PH   SC PH2       NaN      NaN  NaN  NaN
6607  502919       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6608  505288       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6609  510915       NaN      NaN  SC PH   SC PH2       NaN      NaN  NaN  NaN
6610  511804       NaN      NaN  SC PH   SC PH2       NaN      NaN  NaN  NaN
6611  512029       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6612  513156       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6613  514811       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6614  516038       NaN      NaN  UR PH   ST PH1       NaN      NaN  NaN  NaN
6615  516199       NaN      NaN  UR PH  OBC PH1       NaN      NaN  NaN  NaN
6616  517108       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6619  530291       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6620  531574       NaN      NaN  UR PH   UR PH1       NaN      NaN  NaN  NaN
6624  541367       NaN      NaN  SC PH   SC PH2       NaN      NaN  NaN  NaN
6625  547950       NaN      NaN  SC PH   SC PH2       NaN      NaN  NaN  NaN

[2625 rows x 9 columns]